build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_USERNAME: "jgsogo"
    CONAN_LOGIN_USERNAME: "jgsogo"
    CONAN_CHANNEL: "testing"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/jgsogo/conan-packages"
    CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
